<?php

namespace WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DetailPlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailPlanningRepository extends EntityRepository
{
}
