<?php

namespace WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageSponsorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSponsorRepository extends EntityRepository
{
}
