<?php

namespace WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageHotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageHotelRepository extends EntityRepository
{
}
