<?php

namespace WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageSpeakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSpeakerRepository extends EntityRepository
{
}
